services:
  - type: web
    name: op-pox-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn proxy_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
